name: sheshield
description: A women's safety app with emergency features.
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  camera: ^0.10.5+9
  googleapis: ^11.4.0
  googleapis_auth: ^1.4.1
  http: ^0.13.6
  path_provider: ^2.1.2
  shared_preferences: ^2.2.2
  permission_handler: ^11.2.0
  just_audio: ^0.9.36
  path: ^1.8.3
  uuid: ^4.3.3
  device_info_plus: ^9.1.2
  record: ^5.0.4
  geolocator: ^10.1.0
  url_launcher: ^6.2.4
  cloud_firestore: ^4.15.5
  firebase_core: ^2.24.2
  firebase_storage: ^11.6.0
  app_settings: ^5.1.1
  audio_session: ^0.1.18
  flutter_contacts: ^1.1.7+1
  flutter_foreground_task: ^5.1.3
  telephony: ^0.2.0
  flutter_compass: ^0.8.0
  firebase_database: ^10.4.0
  intl: ^0.19.0
  video_player: ^2.8.2
  audioplayers: ^5.2.1
  whatsapp_unilink: ^2.0.1
  synchronized: ^3.1.0
  share_plus: ^7.2.1
  flutter_launcher_icons: ^0.14.3

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
  
  # Commented out until assets are added
  # assets:
  #   - assets/images/
  #   - assets/audio/
  #   - assets/icons/
  
  # Commented out until fonts are added
  # fonts:
  #   - family: Poppins
  #     fonts:
  #       - asset: assets/fonts/Poppins-Regular.ttf
  #       - asset: assets/fonts/Poppins-Bold.ttf
  #         weight: 700
  #       - asset: assets/fonts/Poppins-SemiBold.ttf
  #         weight: 600
  #       - asset: assets/fonts/Poppins-Medium.ttf
  #         weight: 500
  #       - asset: assets/fonts/Poppins-Light.ttf
  #         weight: 300
  